### ISSUE TITLE
IBrowse 2.4 & Aweb APL Lite 3.5.09 on AmigaOS 3.1.4

### ISSUE THREAD

**Issue by frakswe** [ttalvitie/browservice#1]
Doesn't appear to work,i've not done anything else besides opening up the programs and entered
127.0.0.1:8080 in the addressfield.

**Comment by ttalvitie** [comment]
Unfortunately I don't have access to an Amiga computer, so I cannot debug this myself (if someone wants to, then please do!)

I'm wondering what is your networking setup? As the Browservice proxy is probably not running on the Amiga machine, how can you connect to it through 127.0.0.1:8080? Is there some kind of tunneling?

It would also be useful to hear what happens when you try to connect the client browser to Browservice. Do you get an error message, an empty page or something else? What kind output do you get in the Browservice proxy output? If IBrowse/Aweb manages to connect to Browservice, then it should output something like the following (with different numbers):

```
[0623/135009.905989:INFO:session.cpp(342)] Opening session 4612199502597610427
[0623/135009.993082:INFO:session.cpp(138)] CEF browser for session 4612199502597610427 created
```

**Comment by frakswe** [comment]
via amiga emulator, fs-uae.

i just get an empty page at first glance but i'll see if i can get some sort of output...been ages since i used amiga and these browsers.

**Comment by frakswe** [comment]
terminal output:
`[0623/200917.229044:INFO:session.cpp(342)] Opening session 8179018501105408060
[0623/200917.231080:INFO:session.cpp(138)] CEF browser for session 8179018501105408060 created
[0623/200930.339799:INFO:session.cpp(765)] Inactivity timeout for session 18023992176432605612 reached
[0623/200930.339842:INFO:session.cpp(396)] Closing session 18023992176432605612 requested
[0623/200930.339887:INFO:session.cpp(158)] Session 18023992176432605612 closed
[0623/200947.247305:INFO:session.cpp(765)] Inactivity timeout for session 8179018501105408060 reached
[0623/200947.247395:INFO:session.cpp(396)] Closing session 8179018501105408060 requested
[0623/200947.247457:INFO:session.cpp(158)] Session 8179018501105408060 closed
`

**Comment by frakswe** [comment]
html content:
`<html>
<head>
<title>Browservice</title>
<script type="text/javascript">
window.onload = function() {
    window.location.href = "/14207105529457275365/prev/";
};
</script>
</head>
<body>
</body>
</html>`

**Comment by ttalvitie** [comment]
The Browservice log and the HTML content are as expected: the session is created and it serves the HTML page that redirects to the start of the redirect sequence that will eventually lead to the session page. For some reason, this JavaScript redirect code does not work in the browser. You could try to follow the redirects manually (by finding the next URL in the HTML code and following it within 30 seconds of the page load to avoid timeout). You could also try to see if the browser has a developer/javascript/error console and look at what kind of errors it shows. However, my guess is that quite a bit of work is required to make the rest of the JavaScript compatible, so we would need an Amiga user volunteer to tweak the code.

If you just want Browservice to work on Amiga, then the Timberwolf browser could be one option (though I can't really vouch for it, I just found it by searching for Amiga browsers). It is more likely to work out-of-the box, as it is based on Firefox 4, and Browservice has been shown to work on Firefox on other operating systems; however, it seems to require AmigaOS 4. But of course, it would be nice to eventually support IBrowse and Aweb as well.

**Comment by frakswe** [comment]
I merely wanted to try it out for the novelty sake of things, it would've been cool if it worked but it's not the end of the world. Thank you for your time.
