### ISSUE TITLE
Unable To Start Http Server In Port 80

### ISSUE THREAD

**Issue by Jeremy823** [ttalvitie/browservice#109]
Os: Ubuntu Server On Raspberry Pi 4B

jeremy@raspberrypi:~$ ./browservice-v0.9.7.1-aarch64.AppImage --vice-opt-http-listen-addr=0.0.0.0:80
INFO @ src/main.cpp:200 -- Loading vice plugin retrojsvice.so
INFO @ src/main.cpp:207 -- Initializing vice plugin retrojsvice.so
INFO @ retrojsvice.so src/context.cpp:281 -- Creating retrojsvice plugin context
INFO @ src/xvfb.cpp:64 -- Starting Xvfb X server as child process
INFO @ src/xvfb.cpp:135 -- Xvfb X server :0 successfully started
[1025/141455.825878:WARNING:chrome_browser_cloud_management_controller.cc(88)] Could not create policy manager as CBCM is not enabled.
[1025/141455.971940:ERROR:gl_factory.cc(120)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default),(gl=egl-gles2,angle=none)].
[1025/141456.031533:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
INFO @ retrojsvice.so src/context.cpp:338 -- Starting plugin
INFO @ retrojsvice.so src/http.cpp:620 -- Starting HTTP server (listen address: 0.0.0.0:80)
PANIC @ retrojsvice.so src/http.cpp:625: Starting Poco HTTP server failed with exception: I/O error: Permission denied
/tmp/.mount_browseDvcwWM/AppRun: line 128: 13214 Aborted                 (core dumped) ( exec -a "${ARGV0}" "${ROOT}/opt/browservice/browservice" "$@" )

**Comment by farsighter** [comment]
In Linux, only the root user can bind port 80. If you're not running the application as root, you'll encounter a "Permission denied" error when trying to bind to ports below 1024

**Comment by Jeremy823** [comment]
Thanks

**Comment by Jeremy823** [comment]
When I trying run with sudo this happen: 
jeremy@raspberrypi:~/Downloads $ sudo ./browservice-v0.9.7.1-aarch64.AppImage --vice-opt-http-listen-addr=0.0.0.0:80
----------------------------------------------------------------------------------------------------
WARNING: The Verdana font is not installed in '/root/.browservice/appimage/fonts/Verdana.ttf'
         Browservice GUI appearance will be suboptimal.
         Run './browservice-v0.9.7.1-aarch64.AppImage --install-verdana' to install it.
----------------------------------------------------------------------------------------------------
INFO @ src/main.cpp:200 -- Loading vice plugin retrojsvice.so
INFO @ src/main.cpp:207 -- Initializing vice plugin retrojsvice.so
INFO @ retrojsvice.so src/context.cpp:281 -- Creating retrojsvice plugin context
INFO @ src/xvfb.cpp:64 -- Starting Xvfb X server as child process
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
INFO @ src/xvfb.cpp:135 -- Xvfb X server :1 successfully started
[1028/160758.911737:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by Jeremy823** [comment]
And when I try with --no-sandbox
```
jeremy@raspberrypi:~/Downloads $ sudo ./browservice-v0.9.7.1-aarch64.AppImage --vice-opt-http-listen-addr=0.0.0.0:80 --no-sandbox
----------------------------------------------------------------------------------------------------
WARNING: The Verdana font is not installed in '/root/.browservice/appimage/fonts/Verdana.ttf'
         Browservice GUI appearance will be suboptimal.
         Run './browservice-v0.9.7.1-aarch64.AppImage --install-verdana' to install it.
----------------------------------------------------------------------------------------------------
ERROR: Unrecognized option '--no-sandbox'
Try './browservice-v0.9.7.1-aarch64.AppImage --help' for list of supported options

```

**Comment by farsighter** [comment]
--chromium-args=no-sandbox

**Comment by Jeremy823** [comment]
thanks
