### ISSUE TITLE
FAIL: Patching automate-git.py script failed

### ISSUE THREAD

**Issue by bcharden** [ttalvitie/browservice#134]
Hello, I am trying to setup browservice on my Dell Optiplex 745 SFF with a intel core 2 quad running ubuntu 
Ubuntu 20.04.6 LTS. I installed docker on it and when I was following your guide to build the CEF I get the following error here is the output of the terminal 

root@dell-optiplex-745:/home/bcharden/Desktop/browservice/browservice/tools# sudo docker run -v "${PWD}/build":/home/appuser cefbuild python3 /home/appuser/build_patched_cef.py /home/appuser/build /home/appuser/patched_cef_x86_64.tar.bz2 x86_64
--- Creating build dir '/home/appuser/build'
--- Downloading CEF automate-git.py to '/home/appuser/build/automate-git.py'
--- Installing script for applying Browservice-specific CEF/Chromium patches to '/home/appuser/build/browservice_cef_patcher.py'
--- Creating patched automate-git.py script '/home/appuser/build/patched-automate-git.py' that will apply browservice_cef_patcher.py before building CEF
FAIL: Patching automate-git.py script failed
root@dell-optiplex-745:/home/bcharden/Desktop/browservice/browservice/tools#

**Comment by ttalvitie** [comment]
Thanks for the heads up, I also saw this issue in the latest build. After changes to CEF automate-git.py, the patch had become outdated. I fixed this in https://github.com/ttalvitie/browservice/commit/63f0dc13fb5382bb4311bc1856de808b3643e03b (included in latest release and master). Please open a new issue if the problem persists.
