### ISSUE TITLE
Does not work on raspberry pi 3

### ISSUE THREAD

**Issue by kenan1099** [ttalvitie/browservice#15]
The program starts but prints the following message
`[0209/223559.090393:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.`

**Comment by ttalvitie** [comment]
Are you sure that it does not work? That log message is quite common (it is not from Browservice, but from Chromium/CEF), and Browservice usually works even if it prints that. Does the program terminate after the message? What else does it print?

**Comment by kenan1099** [comment]
It does not print anything else, and trying to connect to the server does absolutely nothing on the client side. The program does not terminate after the message.
The program overall prints
`INFO @ src/xvfb.cpp:60 -- Starting Xvfb X server as child process
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
INFO @ src/xvfb.cpp:131 -- Xvfb X server :2 successfully started
INFO @ src/http.cpp:280 -- HTTP server listening to 127.0.0.1:8080
[0210/194949.116043:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
`

**Comment by ttalvitie** [comment]
This output seems completely normal. In your case, it seems that the server has been configured to only listen to local connections (`HTTP server listening to 127.0.0.1:8080`). Are you sure you are connecting from localhost? If you run `curl localhost:8080` on the machine running Browservice, what do you get as output?

**Comment by kenan1099** [comment]
I get

```
<html>
<head>
<title>Browservice</title>
<script type="text/javascript">
window.onload = function() {
    window.location.href = "/2541567326046024394/prev/";
};
</script>
</head>
<body>
</body>
</html>

So the problem might be with my connection instead.

```

**Comment by kenan1099** [comment]
:facepalm: I was connected to another network.
Sorry for the waste of time.
The CEF error threw me off so I immediately jumped to conclusions.
