### ISSUE TITLE
Missing Fonts when showing Chinese and Japanese Characters

### ISSUE THREAD

**Issue by JamesLewisLiu** [ttalvitie/browservice#17]
![image](https://user-images.githubusercontent.com/17558260/108647395-85775f80-74f3-11eb-8f0d-8642ea0dbcdd.png)
Randomly testing some page and found Chinese and Japanese Characters cannot show properly

**Comment by ttalvitie** [comment]
This should be a matter of installing fonts that support Chinese and Japanese characters to the Linux system running browservice. On my Ubuntu 20.04 testing VM, I was able to reproduce the issue, and running
```
sudo apt-get install font-noto-cjk
```
made the characters visible. This only installs Google Noto fonts; you might want to install other font packages as well.

**Comment by JamesLewisLiu** [comment]
Thanks,it works
