### ISSUE TITLE
Error 2 on make retrojsvice.co on Raspberry 3

### ISSUE THREAD

**Issue by matti157** [ttalvitie/browservice#21]
The make command does not finish correctly. Booted on a Raspberry 3B with newly installed raspberry os lite.
![image](https://user-images.githubusercontent.com/76459129/109440297-1a1d1880-7a32-11eb-86da-c61baccf86a9.png)

**Comment by ttalvitie** [comment]
The file permission bits for `viceplugins/retrojsvice/gen_html_cpp.py` seem to be set incorrectly. It should have the execute permission; if you run `ls -l viceplugins/retrojsvice/gen_html_cpp.py`, the output should start with `-rwxr-xr-x` (x for execute permission).

How did you extract the browservice release zip/tarball? If you copied the contents in a way that does not preserve UNIX file permissions, then the permissions will be incorrect. One sure way to extract it correctly is to run the following on the Raspberry Pi:

```
wget https://github.com/ttalvitie/browservice/archive/v0.9.2.0.tar.gz
tar xzf v0.9.2.0.tar.gz
cd browservice-0.9.2.0/
# Start installing Browservice
```

**Comment by matti157** [comment]
Last night I didn't want to play with the terminal commands and I copied the files on the raspberry already extracted ....

Now unzipping the tar from the raspberry works, thanks. And congratulations on this project
