### ISSUE TITLE
Secure Dns Support?

### ISSUE THREAD

**Issue by JadenJSJ** [ttalvitie/browservice#22]
I have the isp force its own dns, which makes things slow I use the secure dns option on chrome 
Secure Dns Option is below
![image](https://user-images.githubusercontent.com/44781632/109742064-f52ad000-7c00-11eb-86e7-5b9f36bb8a6d.png)

This is with the option enabled
![image](https://user-images.githubusercontent.com/44781632/109742155-286d5f00-7c01-11eb-9395-301fce2819ff.png)

And this is the flags I tried to make browservice work with

$ `./browservice --vice-opt-http-listen-addr=0.0.0.0:8080 --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" --enable-features="DnsOverHttps<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:Fallback/true/Templates/https%3A%2F%2Fcloudflare-dns.com%2Fdns-query"                           ERROR: Unrecognized option '--enable-features=DnsOverHttps<DoHTrial'
Try './browservice --help' for list of supported options
$ `

Maybe an option to change browser specific dns on the future?
![image](https://user-images.githubusercontent.com/44781632/109742367-7a15e980-7c01-11eb-8d51-27751fa38124.png)

My Isp forces its dns
![image](https://user-images.githubusercontent.com/44781632/109742597-e98bd900-7c01-11eb-8458-97694f10097e.png)

This is the results of https://1.1.1.1/help
https://1.1.1.1/help#eyJpc0NmIjoiTm8iLCJpc0RvdCI6Ik5vIiwiaXNEb2giOiJObyIsInJlc29sdmVySXAtMS4xLjEuMSI6IlllcyIsInJlc29sdmVySXAtMS4wLjAuMSI6IlllcyIsInJlc29sdmVySXAtMjYwNjo0NzAwOjQ3MDA6OjExMTEiOiJObyIsInJlc29sdmVySXAtMjYwNjo0NzAwOjQ3MDA6OjEwMDEiOiJObyIsImRhdGFjZW50ZXJMb2NhdGlvbiI6IkNHSyIsImlzV2FycCI6Ik5vIiwiaXNwTmFtZSI6IkZpcnN0TWVkaWEiLCJpc3BBc24iOiIyMzcwMCJ9

Thanks for reading

**Comment by ttalvitie** [comment]
Browservice does not accept Chromium command line arguments directly; they must be wrapped in a `--chromium-args` argument, as follows:
```--chromium-args="enable-features=DnsOverHttps<DoHTrial,force-fieldtrials=DoHTrial/Group1,force-fieldtrial-params=DoHTrial.Group1:Fallback/true/Templates/https%3A%2F%2Fcloudflare-dns.com%2Fdns-query"```

However, I could not get this to work (the test page says that DNS over HTTPS is not being used). It seems that these flags do not work in CEF at the moment; at least I had the same problem when using your flags with `cefclient` (to try it, use the instructions in [this issue comment](https://github.com/ttalvitie/browservice/issues/19#issuecomment-786877170)). You should ask CEF forums about the status of secure DNS support in CEF (the [previous thread](https://magpcss.org/ceforum/viewtopic.php?f=6&t=17415) is already one year old); once it works there, it probably should work in Browservice as well.

**Comment by JadenJSJ** [comment]
Oh ok thank you so much ill ask the cef forums
