### ISSUE TITLE
Startup crash with "Could not resolve keysym XF86FullScreen"

### ISSUE THREAD

**Issue by johnassel** [ttalvitie/browservice#23]
Hi,

I tried to install 0.9.2.0 which went fine after the instructions in the readme.

Now when it is starting it is quitting with the following messages:

`[root@johnassel browservice-0.9.2.0]# ./release/bin/browservice --vice-opt-http-listen-addr=192.168.24.1:8081
INFO @ src/main.cpp:126 -- Loading vice plugin retrojsvice.so
INFO @ src/main.cpp:133 -- Initializing vice plugin retrojsvice.so
INFO @ retrojsvice.so src/context.cpp:251 -- Creating retrojsvice plugin context
INFO @ src/xvfb.cpp:62 -- Starting Xvfb X server as child process
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
INFO @ src/xvfb.cpp:133 -- Xvfb X server :0 successfully started
[0315/123202.900450:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[root@johnassel browservice-0.9.2.0]# The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server`

Whats wrong here? Previous versions are running fine.

**Comment by ttalvitie** [comment]
The XKEYBOARD warning message is not fatal (I got it on one of the Linux distros I tried and simply ignored it). The fatal error is this one:
```
[0315/123202.900450:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
This is because you are running browservice as the root user. Even if it running it as root was possible, you should always run it as a regular user for security.

**Comment by johnassel** [comment]
Ah yes - I see. Normally Browservice is running under an unprivileged user - that was a test run to see if the update went correct. Starting it under the other user works without problems again.
