### ISSUE TITLE
Change URL from the client browser

### ISSUE THREAD

**Issue by limacohen** [ttalvitie/browservice#39]
I know we can use the `--start-page` command line option to specify the initial page in the server, but I'm trying to do it from the client (browser). And not from the fake address bar in the CEF browser, since that one [won't trigger the virtual keyboard](https://github.com/ttalvitie/browservice/issues/34) in some devices, thus requiring the aid of an external input.

I'm thinking something like `http://{IP}:{PORT}/{SESSION}/{URL}` or anything that can send a new location to the server and change the output to the client.

This would not only help with [compatibility on some touch devices](https://github.com/ttalvitie/browservice/issues/16) but also be faster to type and allow the creation of shortcuts to different pages without the need to restart the server.

**Comment by ttalvitie** [comment]
Seems useful and doable. I'm thinking there could be two ways to use this.
- Navigating an existing browser session: if the user has already opened a window, and it has for example URL `http://localhost:8080/1/ceWQBGJL4ertCqcExApn8uzx1EXXkyCr/`, then the user can append `goto/` and the desired address to the address bar. For example to go to `google.com`, the user changes the address in the real address bar to `http://localhost:8080/1/ceWQBGJL4ertCqcExApn8uzx1EXXkyCr/goto/google.com` and the window navigates as if the user had written `google.com` to the fake address bar.
- Opening a new browser session: the user navigates to `http://localhost:8080/goto/google.com` and the proxy server starts a new browser that starts from `google.com`.

**Comment by ttalvitie** [comment]
Implemented in 7dc7b19f7e7eee68931427caf1517ce1864c18e4; will be included in the next release.

**Comment by ttalvitie** [comment]
Released in v0.9.3.0. If there are problems with it, open a new issue.
