### ISSUE TITLE
Add disable sandbox option

### ISSUE THREAD

**Issue by WMCB-Tech** [ttalvitie/browservice#4]
Currently I'm using WSL 1 as i have difficulty connecting with browservice server with WSL2, and once i launched borwservice server in WSL1, i have noticed that it doesn't support chromium ipc namespaces so usually i have to append no sandbox

But is there an option to disable sandbox? because i was currently using WSL1

**Comment by ttalvitie** [comment]
I added an option `--chromium-args` for passing extra options to Chromium in e542cbe937a4335954ddf6f8ecca5ec7e6e0a1cb. So to disable the sandbox, try running the master version with the option `--chromium-args=no-sandbox` and let me know if that solved your problem. Please note that running Chromium without sandbox is insecure.

(P.S. Sometimes, I also have problems connecting to local servers running in WSL2 from the Windows side; in these cases, it usually helps to restart WSL2 by running `wsl --shutdown` in the Windows command prompt. Of course, setting up connections from other PCs in the network is still cumbersome.)

**Comment by WMCB-Tech** [comment]
Ok. i switched to wsl1 and enabled no sandbox but instead of giving me ipc namespace error, it gives me about udev and core dumped
![image](https://user-images.githubusercontent.com/65075766/104731257-69570480-5776-11eb-8e82-b13ae14f651c.png)

However i might try to run this with Ubuntu VM with bridged network

**Comment by WMCB-Tech** [comment]
Ok, so I've used Termux as to run browservice and it works (although no sandbox needs to be enabled and took a long time to compile) and yeah it runs

![Screenshot_2021-01-16-12-13-12-06.jpg](https://user-images.githubusercontent.com/65075766/104796788-5aaf3280-57f4-11eb-8d54-645aa610b5c9.jpg)

and the localhost of web server loads,
