### ISSUE TITLE
Add Popup Alert, Confirm, and Prompt box javascript for Browservice

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [ttalvitie/browservice#47]
Alert Box
![image](https://user-images.githubusercontent.com/30205044/122667200-cbaba980-d1db-11eb-9b19-5d5babb45ed2.png)
<pre>
function myFunction() {
alert("I am an alert box!");
}
</pre>
and Line break for Alert box
<pre>alert("Hello\nHow are you?");</pre>

Confirm Box
![image](https://user-images.githubusercontent.com/30205044/122667252-15948f80-d1dc-11eb-9b57-68f897c5f773.png)
<pre>
function myFunction() {
  var txt;
  if (confirm("Press a button!")) {
    txt = "You pressed OK!";
  } else {
    txt = "You pressed Cancel!";
  }
  document.getElementById("demo").innerHTML = txt;
}
</pre>

Prompt Box
![image](https://user-images.githubusercontent.com/30205044/122667285-3bba2f80-d1dc-11eb-877c-eeb82ba706e7.png)
<pre>
function myFunction() {
  var txt;
  var person = prompt("Please enter your name:", "Harry Potter");
  if (person == null || person == "") {
    txt = "User cancelled the prompt.";
  } else {
    txt = "Hello " + person + "! How are you today?";
  }
  document.getElementById("demo").innerHTML = txt;
}</pre>
![image](https://user-images.githubusercontent.com/30205044/122667402-fc401300-d1dc-11eb-81ba-17704935073c.png)

but Popup Box Alert, Confirm, and Prompt Box is not displayed on browservice?
Try this [link](https://www.w3schools.com/js/js_popup.asp):
[W3schools JS Popup](https://www.w3schools.com/js/js_popup.asp)

**Comment by ttalvitie** [comment]
I think at some point in the development, I came to believe that supporting alert/prompt windows with the CEF off-screen rendering mode that Browservice uses is difficult or impossible, but I could be mistaken. I should try to have a second look at some point on whether this could be done.

How important are alert/prompt windows in the modern web? I think those are nowadays typically implemented by adding an overlay div element.

**Comment by achmadsutardi441953** [comment]
yes this popup alert/prompt dialog on browservice
