### ISSUE TITLE
The setuid sandbox provides API version 1, but you need 0

### ISSUE THREAD

**Issue by wolfo** [ttalvitie/browservice#5]
Hi, browservice 0.9.1.2 won't start for me, complaining about a wrong API version.

```
$ release/bin/chrome-sandbox --http-listen-addr=0.0.0.0:8080
The setuid sandbox provides API version 1, but you need 0
Please read https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md.

close: Bad file descriptor
Read on socketpair: Success
```

Other things I tried that just triggered the same message:
- ``chrome-sandbox --help``
- Removing the SUID bit and running via sudo
- ``sudo release/bin/chrome-sandbox --http-listen-addr=0.0.0.0:8080 --disable-setuid-sandbox``

Running it without arguments, as per the example in the Readme, it just complains about missing arguments:

```
$ release/bin/chrome-sandbox
Usage: release/bin/chrome-sandbox <renderer process> <args...>
```

The link in the error message describes how to update the setuid binary in the context of installing chrome or chrome-sandbox itself. However, it doesn't seem to be included in the browservice source and it isn't mentioned in its documentation anyway.

### How I built it:

- Debian GNU/Linux 10, Kernel 4.19.0-12-amd64
- It's a headless setup, if that makes a difference
- Installed requirements:
``apt install wget cmake g++ pkg-config libxcb1-dev libx11-dev libpoco-dev libjpeg-dev zlib1g-dev libpango1.0-dev libpangoft2-1.0-0 ttf-mscorefonts-installer xvfb xauth libatk-bridge2.0-0 libasound2 libgbm1 libxi6 libcups2 libnss3 libxcursor1 libxrandr2 libxcomposite1 libxss1 libxkbcommon0``
- And of course:
``./download_cef.sh``
``./setup_cef.sh``
``make -j4``
``sudo chown root:root release/bin/chrome-sandbox``
``sudo chmod 4755 release/bin/chrome-sandbox``

**Comment by ttalvitie** [comment]
I think you are running the wrong executable. You are not supposed to invoke `chrome-sandbox` directly; it is used internally by CEF. In the README, it says that you should start the `browservice` executable using the command:
```release/bin/browservice```
Does the above command work?

**Comment by wolfo** [comment]
Oh man. I must have just kept the binary path after chmodding the sandbox. My bad!

Can't wait to try this out on a few old machines! :-)
