### ISSUE TITLE
Can Watching Streaming netflix on Browservice but DRM Widevine is Not working?

### ISSUE THREAD

**Issue by JeremyLyokoPPG2020** [ttalvitie/browservice#51]
DRM Widevine Not work on Browservice. Can watch movies on browservice??
`include/cef_web_plugin.h` How to enable Widevine DRM?

**Comment by okyanusoz** [comment]
Maybe this can help: https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=17719

**Comment by ttalvitie** [comment]
I'm not planning on officially supporting Widevine on Browservice or even testing it due to the legal issues around that, so I can't help you with this issue. But you may of course discuss setting it up with other people here.
