### ISSUE TITLE
Mac OS Classic, Mac OS X PowerPC and NeXT Platforms ?

### ISSUE THREAD

**Issue by Hawk2811** [ttalvitie/browservice#55]
Please add support to Mac OS 7 to 9 Classic and OSX PowerPC 

It Would Be Cool To Use Internet on a Mac II, ibook g3 and NeXTStation

**Comment by IoIxD** [comment]
What problems do you currently have using BrowService on those platforms?

**Comment by Hawk2811** [comment]
But is it the compatibility list in the repository's README.md?

**Comment by ttalvitie** [comment]
I assume that you mean running the client on Mac OS 7 to 9 Classic and OSX PowerPC. It may or may not work, depending on the browser; you can try it out if you want. The compatibility list is not exhaustive; I cannot test all machines and browsers as I don't have the necessary hardware or time/expertise to set up emulated environments.

The proxy server cannot run on PowerPC machines as Chromium Embedded Framework does not support them.

**Comment by erichelgeson** [comment]
I tested on
[Classilla 9.3.4b](https://sourceforge.net/projects/classilla/)
Does not seem to evaluate the JS - just sits at the page with the window.href = 

[Internet Explorer 5 & 5.1](https://macintoshgarden.org/apps/internet-explorer-517)
Goes into a redirect loop of `/xx/<id>/` to `/xx/<id>/next`

[Netscape 4.75](https://macintoshgarden.org/apps/netscape-communicator-48)
Loads but shows broken images and an input box, Putting a URL in the input box results in `ERROR: Invalid window handle`

I can gather more info if you'd like, just ask. If you want an easy setup to test you can try out [macintosh.js ](https://github.com/felixrieseberg/macintosh.js)- a pre-configured emulator.

**Comment by kriddile** [comment]
> I tested browserservice(win) v0.9.4.0 using a Pismo G3 Laptop running Mac OS 9.2.1 with:
> 
> [Classilla 9.3.4b](https://sourceforge.net/projects/classilla/) Does not seem to evaluate the JS - just sits at the page with the window.href =
> 
> [Internet Explorer 5 & 5.1](https://macintoshgarden.org/apps/internet-explorer-517) Goes into a redirect loop of `/xx/<id>/` to `/xx/<id>/next`
> 
> [Netscape 4.75](https://macintoshgarden.org/apps/netscape-communicator-48) Loads but shows broken images and an input box, Putting a URL in the input box results in `ERROR: Invalid window handle`
> 
> I can gather more info if you'd like, just ask. If you want an easy setup to test you can try out [macintosh.js ](https://github.com/felixrieseberg/macintosh.js)- a pre-configured emulator.

I have the same IE 5 and Netscape behavior on Mac OS 8.6 when connecting to browservice(win) v0.9.6.3.

**Comment by lampiaio** [comment]
I also get the same results as above. iCab loads the image with some strong artifacts and keyboard input doesn't work. But you know what's weird? Some guy on the Macintosh Garden discord server got it working in 2021 with IE 5.0... I have no idea how.

![image](https://user-images.githubusercontent.com/105524471/223611613-d1be20df-25e0-424f-a3ad-c2879cc73c65.png)

If someone wants to try asking them, here's the [link to the message](https://discord.com/channels/441926336605585408/460026391673569310/811274552650498088). (The internet has left me too jaded/traumatized from similar past situations to try contacting them and asking what they did, I apologize. Can't set myself up for another instance of "oh haha sorry yeah I can't remember what I did / it just worked for me at the time, sorry can't help you")...
