### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by D-06** [ttalvitie/browservice#59]
chown: cannot access 'browservice-v0.9.4.0-aarch64.AppDir/opt/browservice/chrome-sandbox': No such file or directory

**Comment by ttalvitie** [comment]
Could you give more details, i.e. what are you trying to do, the commands you ran before this and their outputs?

I assume that you are following the second option in the troubleshooting section [SUID sandbox helper not found](https://github.com/ttalvitie/browservice#suid-sandbox-helper-not-found). Did the AppImage extraction run successfully? Are you sure that you are running an AArch64 machine (`uname -m` will reveal this).

**Comment by D-06** [comment]
Oh i forgot to change ARCH and RELEASE
but for some reason this still pop up
```
root@localhost:~# sudo chown root:root browservice-v0.9.4.0-aarch64.AppDir/opt/browservice/chrome-sandbox
root@localhost:~# sudo chmod 4755 browservice-v0.9.4.0-aarch64.AppDir/opt/browservice/chrome-sandbox
root@localhost:~# su - dat
dat@localhost:~$ cd /root                            dat@localhost:/root$ ls
Downloads
browservice-v0.9.4.0-aarch64.AppDir                  browservice-v0.9.4.0-aarch64.AppImage
dat@localhost:/root$ browservice-v0.9.4.0-aarch64.AppDir/AppRun                                           INFO @ src/main.cpp:200 -- Loading vice plugin retrojsvice.so
INFO @ src/main.cpp:207 -- Initializing vice plugin retrojsvice.so
INFO @ retrojsvice.so src/context.cpp:281 -- Creating retrojsvice plugin context                          INFO @ src/xvfb.cpp:64 -- Starting Xvfb X server as child process
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running                                             _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
INFO @ src/xvfb.cpp:135 -- Xvfb X server :2 successfully started
[0109/032559.580077:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /root/browservice-v0.9.4.0-aarch64.AppDir/opt/browservice/chrome-sandbox is owned by root and has mode 4755.
browservice-v0.9.4.0-aarch64.AppDir/AppRun: line 128: 31849 Trace/breakpoint trap   "${ROOT}/opt/browservice/browservice" "$@"                                 [0100/000000.677542:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
```

**Comment by ttalvitie** [comment]
Could you please provide a full log of the commands and their outputs, including the browservice AppImage extraction (which has been omitted so far). In addition, please specify which Linux distribution (including the version) you are running.

I'm asking because your file and permission configuration is very atypical (typically, normal users should NOT have access to `/root`; you can extract the AppImage in the home directory of the normal user dat and only use sudo to chown and chmod `chrome-sandbox`), and knowing more about the Linux distribution would help me try to reproduce your issue.
