### ISSUE TITLE
Cant sign in too google (Manjaro ~ Arch distro)

### ISSUE THREAD

**Issue by JadenJSJ** [ttalvitie/browservice#6]
Yes I changed issues.
I can't sign in to my google account
maybe away to update chrome?
Its Chromium 87

![image](https://user-images.githubusercontent.com/44781632/104728553-a2d54300-5769-11eb-8252-1ee7b0966da0.png)

**Comment by ttalvitie** [comment]
Google seems to block logins using CEF (CEF is not typically used for web browsers like Browservice; it is more often used for embedded login screens, which should be using things like OAuth instead).

I was able to get around this by changing the user agent header to that of Firefox by adding the command line option `--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"`. However, this is not guaranteed to always work in the future.

**Comment by JadenJSJ** [comment]
Oh thanks that was one quick response ngl

**Comment by ttalvitie** [comment]
Just to confirm, @JadenJSJ, did changing the user agent fix the problem in your case?

**Comment by JadenJSJ** [comment]
> Just to confirm, @JadenJSJ, did changing the user agent fix the problem in your case?

Yes

**Comment by Littlemac123** [comment]
> Google seems to block logins using CEF (CEF is not typically used for web browsers like Browservice; it is more often used for embedded login screens, which should be using things like OAuth instead).
> 
> I was able to get around this by changing the user agent header to that of Firefox by adding the command line option `--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"`. However, this is not guaranteed to always work in the future.

this didnt work for me and im using linuxmint of the app. google said the same exact thing as this picture said .
my command was ./browservice-v0.9.5.0-x86_64.AppImage --vice-opt-http-listen-addr=0.0.0.0:8080 --data-dir=$HOME/.browservice/cefdata --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
