### ISSUE TITLE
InitializeSandbox error

### ISSUE THREAD

**Issue by Kewun0** [ttalvitie/browservice#7]
Hello, I'm having the following issue:

INFO @ src/xvfb.cpp:60 -- Starting Xvfb X server as child process
INFO @ src/xvfb.cpp:131 -- Xvfb X server :0 successfully started
INFO @ src/http.cpp:280 -- HTTP server listening to 127.0.0.1:8080
[0115/161016.529665:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

I have that error when starting the server. And I can't access the proxy (mysite:8080 refused to connect). Any ideas? Server is on ubuntu 20.04

**Comment by Bobynoby** [comment]
Did you ever figure this out? I seem to be stuck on this as well. Cant connect on port 8080 and followed the installation twice with my SSH console just showing this and nothing else. Ol uncle google doesnt seem to be any help either. Using Arch Linux ARM armv7l on a Raspberry Pi 3 B+

![image](https://user-images.githubusercontent.com/18043550/104807284-b86a6b80-5842-11eb-846f-81b3bbd4565e.png)

**Comment by Kewun0** [comment]
i solved it running it with
release/bin/browservice --http-listen-addr=0.0.0.0:8080

I just forgot to read the instructions clearly, and that sandbox error doesnt seem to matter much but now im able to connect.

**Comment by BobyTheDragon** [comment]
Hmm, Odd I wonder why 0.0.0.0:8080 works but not when I set it to a local IP to listen. Anyway, Seemed to fix it for me. Thanks :)
