### ISSUE TITLE
Browservice doesn't open on HotJava on Solaris 7

### ISSUE THREAD

**Issue by nguyenthienminh** [ttalvitie/browservice#71]
So, Browservice doesn't even want to load on HotJava on Solaris 7. I want to try it because, well, the browser is from the '90s so it can't load modern websites. This is what I get: 
![image](https://user-images.githubusercontent.com/86407326/161365939-b9e82779-928b-46ef-b112-d0c763529681.png)
HotJava does show the Browservice title, so it's clearly not a connection issue.
Trying with /goto/google.com still does absolutely nothing:
![image](https://user-images.githubusercontent.com/86407326/161365965-8764d89d-0bb7-4c52-846e-de69fb4b6e94.png)
Server logs from the cmd window: 
![image](https://user-images.githubusercontent.com/86407326/161365974-e16a2099-6377-45df-a4c0-186bb36ec252.png)
How can I fix this?

**Comment by ttalvitie** [comment]
Browservice has not been tested on HotJava, so I really can't say whether it should work. The client browser must have sufficient JavaScript support. It was a bit difficult to find information on HotJava, but it seems that versions 1.x have no JavaScript support at all (so there's really no chance), but version 3 may have some JavaScript support (but it is unclear whether it is sufficient for Browservice).

I can't say from your screenshots which version you are using. It does not seem to be working at all as the JavaScript-based redirections are not happening.

Currently I don't have much time for improving client browser support, but I can accept good quality patches if someone else wants to do it. If you want something to work out-of-the-box, then you should try [WRP](https://github.com/tenox7/wrp), as it only requires very basic HTML support from the client browser.

**Comment by nguyenthienminh** [comment]
Oh, the HotJava version in the version of Solaris I'm using is HotJava 1.0.2, so yep... no JavaScript support. I just assumed that JavaScript is available on the version of HotJava (because it's from 1999), but turns out it doesn't! Thanks!
