### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by DC7IA** [ttalvitie/browservice#74]
Every single of the AppImages gives me a segmentation fault on a Raspberry Pi:

`[1]    5982 segmentation fault  ./browservice-v0.9.2.2-armhf.AppImage`

I tried every version:

```
browservice-v0.9.2.2-armhf.AppImage
browservice-v0.9.3.0-armhf.AppImage
browservice-v0.9.4.0-armhf.AppImage
browservice-v0.9.5.0-armhf.AppImage
```

Hardware: Raspberry Pi 1B running:

```
$lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by DC7IA** [comment]
Further details, in case that it is useful:

```
cat /proc/cpuinfo
processor	        : 0
model name	        : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	        : 697.95
Features	                : half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture     : 7
CPU variant	        : 0x0
CPU part	                : 0xb76
CPU revision	        : 7

Hardware	        : BCM2835
Revision	                : 000e
Serial		        : *redacted**
Model		        : Raspberry Pi Model B Rev 2
```

(Second revision from 2012)

**Comment by ttalvitie** [comment]
Haven't tested Browservice on ARMv6 Raspberry Pis (that is, original Raspberry Pi and Raspberry Pi Zero; Raspberry Pi 2+ and Zero 2 should be fine). It seems that ARMv6 is not supported for multiple reasons:
- The prebuilt CEF distribution does not support it. (I tried to run the CEF examples on my original Raspberry Pi Zero, and got `Illegal instruction` errors.)
- The AppImage is built using dependencies from Ubuntu for armhf, which requires at least ARMv7.

While you could in theory get around this by building both CEF and Browservice, it probably won't be worth it; the CPU in BCM2835 is so slow that the embedded Chromium browser would run much too slow for any real use. The 512 MB RAM might also be a bit too small. For this reason, I won't be adding support for ARMv6 either.

**Comment by DC7IA** [comment]
Thanks for the clarification.

**Comment by DC7IA** [comment]
Maybe put that in the README.md as well. :)
