### ISSUE TITLE
Can't launch AppImage on RaspBi Os

### ISSUE THREAD

**Issue by Rajmi105** [ttalvitie/browservice#92]
when I try to launch the app it gives me a no such file or directory error

**Comment by ttalvitie** [comment]
If you really want some help with the issue, you need to be a bit more specific. First of all:
- Which Raspberry Pi OS version did you use?
- Which architecture of Raspberry Pi OS did you use: 32-bit (the default) or 64-bit?
- Which version of Browservice did you use?
- How did you launch the AppImage?
- What was exactly the output (a full terminal output, showing how you run the AppImage and ALL of the terminal output you get from it).
