### ISSUE TITLE
Unable to access the page from PCs other than the host

### ISSUE THREAD

**Issue by BreadTeleporter** [ttalvitie/browservice#99]
When I start browservice, it starts on 127.0.0.1, so I am unable to access it from other computers.

How to reproduce:
Start a fresh install of browservice on Windows

**Comment by WunderWungiel** [comment]
Add "--vice-opt-http-listen-addr=0.0.0.0:8080" to browservice command

**Comment by BreadTeleporter** [comment]
That worked, thanks!
